---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
  phpcodesniffer:
    enabled: true
    config:
        standard: "Yii2"
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths: []
